export const achievements = [
  {
    id: 'first_blood',
    name: 'First Blood',
    description: 'Play your first game',
    emoji: '🩸',
    condition: 'games_played >= 1',
    reward: 10,
  },
  {
    id: 'on_a_roll',
    name: 'On a Roll',
    description: 'Reach 5 streak',
    emoji: '🔥',
    condition: 'streak >= 5',
    reward: 20,
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Reach 10 streak',
    emoji: '🚀',
    condition: 'streak >= 10',
    reward: 50,
  },
  {
    id: 'perfect_ten',
    name: 'Perfect Ten',
    description: 'Answer 10 in a row correctly',
    emoji: '💯',
    condition: 'streak >= 10',
    reward: 100,
  },
  {
    id: 'century',
    name: 'Century',
    description: 'Reach 100 total correct answers',
    emoji: '🎉',
    condition: 'correct >= 100',
    reward: 200,
  },
  {
    id: 'scholar',
    name: 'Scholar',
    description: 'Reach 500 correct answers',
    emoji: '🎓',
    condition: 'correct >= 500',
    reward: 500,
  },
  {
    id: 'category_master',
    name: 'Category Master',
    description: '50 correct in one category',
    emoji: '👑',
    condition: 'category_correct >= 50',
    reward: 150,
  },
  {
    id: 'speed_demon',
    name: 'Speed Demon',
    description: 'Answer correctly in under 5 seconds',
    emoji: '⚡',
    condition: 'time_taken < 5',
    reward: 25,
  },
  {
    id: 'comeback_kid',
    name: 'Comeback Kid',
    description: 'Answer correctly after 3 wrong in a row',
    emoji: '🔄',
    condition: 'after_3_wrong',
    reward: 30,
  },
  {
    id: 'daily_grinder',
    name: 'Daily Grinder',
    description: 'Complete 7 daily challenges',
    emoji: '📅',
    condition: 'daily_completed >= 7',
    reward: 70,
  },
  {
    id: 'duel_champion',
    name: 'Duel Champion',
    description: 'Win 10 duels',
    emoji: '⚔️',
    condition: 'duels_won >= 10',
    reward: 100,
  },
  {
    id: 'tournament_victor',
    name: 'Tournament Victor',
    description: 'Win a tournament',
    emoji: '🏆',
    condition: 'tournaments_won >= 1',
    reward: 300,
  },
  {
    id: 'points_millionaire',
    name: 'Points Millionaire',
    description: 'Reach 10,000 points',
    emoji: '💰',
    condition: 'score >= 10000',
    reward: 1000,
  },
  {
    id: 'night_owl',
    name: 'Night Owl',
    description: 'Play between midnight and 4am',
    emoji: '🦉',
    condition: 'played_night',
    reward: 15,
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Play between 5am and 7am',
    emoji: '🐦',
    condition: 'played_early',
    reward: 15,
  },
]